-- Lecture seule : produit le script de recréation complet du schéma (sql/schema_reference.sql).
-- Verbes create et insert passés en argument : l'éditeur SQL Supabase les repère même dans une chaîne et agit sur la table qui suit.
with
tables_app as (
    select c.oid, c.relname, format('%I.%I', n.nspname, c.relname) as nom_complet,
           c.relowner, c.relacl, c.relrowsecurity, c.relforcerowsecurity
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relkind in ('r', 'p')
      and not exists (select 1 from pg_depend d where d.classid = 'pg_class'::regclass and d.objid = c.oid and d.deptype = 'e')
),
sequences_app as (
    select c.oid, c.relname, format('%I.%I', n.nspname, c.relname) as nom_complet, c.relowner, c.relacl
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relkind = 'S'
      and not exists (select 1 from pg_depend d where d.classid = 'pg_class'::regclass and d.objid = c.oid and d.deptype in ('e', 'i'))
),
fonctions_app as (
    select p.oid, p.proname, format('%I.%I(%s)', n.nspname, p.proname, pg_get_function_identity_arguments(p.oid)) as signature,
           p.proowner, p.proacl
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.prokind in ('f', 'p')
      and not exists (select 1 from pg_depend d where d.classid = 'pg_proc'::regclass and d.objid = p.oid and d.deptype = 'e')
),
objets_avec_droits as (
    select nom_complet, 'table' as genre, relowner as proprietaire, coalesce(relacl, acldefault('r', relowner)) as acl
    from tables_app
    union all
    select nom_complet, 'sequence', relowner, coalesce(relacl, acldefault('s', relowner))
    from sequences_app
),
roles_reinitialises as (
    select 'public, anon, authenticated, service_role' as liste
),
policies_app as (
    select *
    from pg_policies
    where schemaname in ('public', 'storage')
),
sections (ordre, titre, contenu) as (
    select 1, 'Extensions', (
        select string_agg(format('%s extension if not exists %I with schema %I;', 'create', e.extname, n.nspname), E'\n' order by e.extname)
        from pg_extension e
        join pg_namespace n on n.oid = e.extnamespace
        where n.nspname = 'public'
    )
    union all
    select 2, 'Séquences', (
        select string_agg(format('%s sequence %s as %s increment %s minvalue %s maxvalue %s start %s cache %s%s;',
                   'create', s.nom_complet, format_type(q.seqtypid, null), q.seqincrement, q.seqmin, q.seqmax, q.seqstart, q.seqcache,
                   case when q.seqcycle then ' cycle' else '' end), E'\n' order by s.relname)
        from sequences_app s
        join pg_sequence q on q.seqrelid = s.oid
    )
    union all
    select 3, 'Tables', (
        select string_agg(format(E'%s table %s (\n%s\n);', 'create', t.nom_complet, colonnes.liste), E'\n\n' order by t.relname)
        from tables_app t
        cross join lateral (
            select string_agg(format('    %I %s%s%s%s',
                       a.attname,
                       format_type(a.atttypid, a.atttypmod),
                       case
                           when a.attgenerated = 's' then format(' generated always as (%s) stored', pg_get_expr(ad.adbin, ad.adrelid))
                           when ad.adbin is not null then ' default ' || pg_get_expr(ad.adbin, ad.adrelid)
                           else ''
                       end,
                       case a.attidentity
                           when 'a' then ' generated always as identity'
                           when 'd' then ' generated by default as identity'
                           else ''
                       end,
                       case when a.attnotnull then ' not null' else '' end
                   ), E',\n' order by a.attnum) as liste
            from pg_attribute a
            left join pg_attrdef ad on ad.adrelid = a.attrelid and ad.adnum = a.attnum
            where a.attrelid = t.oid
              and a.attnum > 0
              and not a.attisdropped
        ) colonnes
    )
    union all
    select 4, 'Propriété des séquences', (
        select string_agg(format('alter sequence %s owned by %s.%I;', s.nom_complet, t.nom_complet, a.attname), E'\n' order by s.relname)
        from sequences_app s
        join pg_depend d on d.classid = 'pg_class'::regclass and d.objid = s.oid and d.deptype = 'a'
        join tables_app t on t.oid = d.refobjid
        join pg_attribute a on a.attrelid = d.refobjid and a.attnum = d.refobjsubid
    )
    union all
    select 5, 'Contraintes', (
        select string_agg(format('alter table %s add constraint %I %s;', t.nom_complet, co.conname, pg_get_constraintdef(co.oid)), E'\n'
                   order by case co.contype when 'p' then 1 when 'u' then 2 when 'x' then 3 when 'c' then 4 else 5 end, t.relname, co.conname)
        from pg_constraint co
        join tables_app t on t.oid = co.conrelid
        where co.contype in ('p', 'u', 'x', 'c', 'f')
    )
    union all
    select 6, 'Index', (
        select string_agg(pg_get_indexdef(i.indexrelid) || ';', E'\n' order by t.relname, ic.relname)
        from pg_index i
        join tables_app t on t.oid = i.indrelid
        join pg_class ic on ic.oid = i.indexrelid
        where not exists (
            select 1 from pg_constraint co
            where co.conindid = i.indexrelid and co.conrelid = i.indrelid and co.contype in ('p', 'u', 'x')
        )
    )
    union all
    select 7, 'Fonctions', (
        select string_agg(pg_get_functiondef(f.oid) || ';', E'\n\n' order by f.proname, f.oid::regprocedure::text)
        from fonctions_app f
    )
    union all
    select 8, 'Déclencheurs', (
        select string_agg(pg_get_triggerdef(tg.oid) || ';', E'\n' order by tg.tgrelid::regclass::text, tg.tgname)
        from pg_trigger tg
        where not tg.tgisinternal
          and (tg.tgrelid in (select oid from tables_app) or tg.tgfoid in (select oid from fonctions_app))
    )
    union all
    select 9, 'Row Level Security', (
        select string_agg(format('alter table %s enable row level security;', t.nom_complet)
                   || case when t.relforcerowsecurity then format(E'\nalter table %s force row level security;', t.nom_complet) else '' end,
                   E'\n' order by t.relname)
        from tables_app t
        where t.relrowsecurity
    )
    union all
    select 10, 'Policies', (
        select string_agg(format(E'create policy %I on %I.%I as %s for %s to %s%s%s;',
                   p.policyname, p.schemaname, p.tablename, lower(p.permissive), lower(p.cmd),
                   (select string_agg(case when r = 'public' then 'public' else quote_ident(r) end, ', ' order by r) from unnest(p.roles) r),
                   case when p.qual is not null then E'\n    using (' || p.qual || ')' else '' end,
                   case when p.with_check is not null then E'\n    with check (' || p.with_check || ')' else '' end),
                   E'\n\n' order by p.schemaname, p.tablename, p.policyname)
        from policies_app p
    )
    union all
    select 11, 'Droits sur les tables et séquences', (
        select string_agg(instruction, E'\n' order by nom_complet, rang, instruction)
        from (
            select o.nom_complet, 0 as rang,
                   format('revoke all on %s %s from %s;', o.genre, o.nom_complet, r.liste) as instruction
            from objets_avec_droits o
            cross join roles_reinitialises r
            union all
            select o.nom_complet, 1,
                   format('grant %s on %s %s to %s;',
                       string_agg(lower(a.privilege_type), ', ' order by a.privilege_type), o.genre, o.nom_complet,
                       case when a.grantee = 0 then 'public' else quote_ident(r.rolname) end)
            from objets_avec_droits o
            cross join lateral aclexplode(o.acl) a
            left join pg_roles r on r.oid = a.grantee
            where a.grantee <> o.proprietaire
            group by o.nom_complet, o.genre, a.grantee, r.rolname
            union all
            select t.nom_complet, 2,
                   format('grant %s (%I) on table %s to %s;',
                       string_agg(lower(a.privilege_type), ', ' order by a.privilege_type), att.attname, t.nom_complet,
                       case when a.grantee = 0 then 'public' else quote_ident(r.rolname) end)
            from tables_app t
            join pg_attribute att on att.attrelid = t.oid and att.attacl is not null and not att.attisdropped
            cross join lateral aclexplode(att.attacl) a
            left join pg_roles r on r.oid = a.grantee
            where a.grantee <> t.relowner
            group by t.nom_complet, att.attname, a.grantee, r.rolname
        ) d
    )
    union all
    select 12, 'Droits d''exécution des fonctions', (
        select string_agg(instruction, E'\n' order by signature, rang, instruction)
        from (
            select f.signature, 0 as rang,
                   format('revoke all on function %s from %s;', f.signature, r.liste) as instruction
            from fonctions_app f
            cross join roles_reinitialises r
            union all
            select f.signature, 1,
                   format('grant execute on function %s to %s;', f.signature,
                       case when a.grantee = 0 then 'public' else quote_ident(r.rolname) end)
            from fonctions_app f
            cross join lateral aclexplode(coalesce(f.proacl, acldefault('f', f.proowner))) a
            left join pg_roles r on r.oid = a.grantee
            where a.grantee <> f.proowner
        ) d
    )
    union all
    select 13, 'Buckets Storage', (
        select string_agg(format('%s into %s (id, name, public, file_size_limit, allowed_mime_types) values (%L, %L, %s, %s, %s);',
                   'insert', 'storage.buckets', b.id, b.name, case when b.public then 'true' else 'false' end,
                   coalesce(b.file_size_limit::text, 'null'),
                   coalesce(quote_literal(b.allowed_mime_types::text) || '::text[]', 'null')), E'\n' order by b.id)
        from storage.buckets b
    )
    union all
    select 14, 'Contrôle : objets non reproduits par ce script', (
        select coalesce(string_agg('-- ' || element, E'\n' order by element), '-- Aucun.')
        from (
            select 'vue ' || relname as element from pg_class
            where relnamespace = 'public'::regnamespace and relkind in ('v', 'm')
            union all
            select 'type ' || t.typname from pg_type t
            where t.typnamespace = 'public'::regnamespace
              and t.typtype in ('e', 'd', 'r', 'c', 'm')
              and not (t.typtype = 'c' and exists (select 1 from pg_class c where c.oid = t.typrelid and c.relkind <> 'c'))
              and not exists (select 1 from pg_depend d where d.classid = 'pg_type'::regclass and d.objid = t.oid and d.deptype = 'e')
            union all
            select 'fonction de type agrégat ou fenêtre ' || proname from pg_proc
            where pronamespace = 'public'::regnamespace and prokind in ('a', 'w')
              and not exists (select 1 from pg_depend d where d.classid = 'pg_proc'::regclass and d.objid = pg_proc.oid and d.deptype = 'e')
            union all
            select 'publication ' || pubname || ' : table ' || tablename from pg_publication_tables
            where schemaname = 'public'
            union all
            select 'propriétaire ' || pg_get_userbyid(relowner) || ' pour la table ' || relname from tables_app
            where relowner <> 'postgres'::regrole
            union all
            select 'propriétaire ' || pg_get_userbyid(proowner) || ' pour la fonction ' || proname from fonctions_app
            where proowner <> 'postgres'::regrole
            union all
            select 'schéma ' || nspname from pg_namespace
            where nspname !~ '^(pg_|_)'
              and nspname not in ('information_schema', 'public', 'auth', 'storage', 'extensions', 'graphql', 'graphql_public',
                                  'realtime', 'supabase_functions', 'supabase_migrations', 'vault', 'pgsodium', 'pgsodium_masks',
                                  'net', 'cron', 'pgbouncer', 'pgmq')
        ) controle
    )
)
select concat_ws(E'\n',
           'begin;',
           'set local check_function_bodies = off;',
           '',
           string_agg(format(E'-- %s\n\n%s\n', titre, contenu), E'\n' order by ordre),
           'commit;'
       ) as schema_reference
from sections
where contenu is not null;
